### ISSUE TITLE
can not open mongo-express

### ISSUE THREAD

**Issue by wzhi05** [BSlience/bigdata-zerotohero#3]
I compose up the docker-compose.yml in serving-database and set <br> rs.initiate(
  {
    _id : 'rs0',
    members: [
      { _id : 0, host : "mongo1:27017" },
      { _id : 1, host : "mongo2:27017" },
      { _id : 2, host : "mongo3:27017" }
    ]
  }
)

**Comment by wzhi05** [comment]
But I still can not open mongo-express in port 8083 <br> Following is logs from mongo-express

**Comment by wzhi05** [comment]
Welcome to mongo-express

------------------------



(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

Could not connect to database using connectionString: mongodb://mongo1:27017"

(node:7) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo1:27017] on first connect [Error: connect ECONNREFUSED 172.18.0.3:27017

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {

  name: 'MongoNetworkError'

}]

    at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)

    at Pool.emit (events.js:314:20)

    at /node_modules/mongodb/lib/core/connection/pool.js:564:14

    at /node_modules/mongodb/lib/core/connection/pool.js:1000:11

    at /node_modules/mongodb/lib/core/connection/connect.js:32:7

    at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)

    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)

    at Object.onceWrapper (events.js:421:26)

    at Socket.emit (events.js:314:20)

    at emitErrorNT (internal/streams/destroy.js:92:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)

    at processTicksAndRejections (internal/process/task_queues.js:84:21)

(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

Could not connect to database using connectionString: mongodb://mongo1:27017"

(node:7) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo1:27017] on first connect [Error: connect ECONNREFUSED 172.18.0.3:27017

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {

  name: 'MongoNetworkError'

}]

    at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)

    at Pool.emit (events.js:314:20)

    at /node_modules/mongodb/lib/core/connection/pool.js:564:14

    at /node_modules/mongodb/lib/core/connection/pool.js:1000:11

    at /node_modules/mongodb/lib/core/connection/connect.js:32:7

    at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)

    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)

    at Object.onceWrapper (events.js:421:26)

    at Socket.emit (events.js:314:20)

    at emitErrorNT (internal/streams/destroy.js:92:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)

    at processTicksAndRejections (internal/process/task_queues.js:84:21)

(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:8) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

Could not connect to database using connectionString: mongodb://mongo1:27017"

(node:8) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo1:27017] on first connect [Error: connect ECONNREFUSED 172.18.0.3:27017

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {

  name: 'MongoNetworkError'

}]

    at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)

    at Pool.emit (events.js:314:20)

    at /node_modules/mongodb/lib/core/connection/pool.js:564:14

    at /node_modules/mongodb/lib/core/connection/pool.js:1000:11

    at /node_modules/mongodb/lib/core/connection/connect.js:32:7

    at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)

    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)

    at Object.onceWrapper (events.js:421:26)

    at Socket.emit (events.js:314:20)

    at emitErrorNT (internal/streams/destroy.js:92:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)

    at processTicksAndRejections (internal/process/task_queues.js:84:21)

(node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

Could not connect to database using connectionString: mongodb://mongo1:27017"

(node:7) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo1:27017] on first connect [Error: connect ECONNREFUSED 172.18.0.3:27017

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {

  name: 'MongoNetworkError'

}]

    at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)

    at Pool.emit (events.js:314:20)

    at /node_modules/mongodb/lib/core/connection/pool.js:564:14

    at /node_modules/mongodb/lib/core/connection/pool.js:1000:11

    at /node_modules/mongodb/lib/core/connection/connect.js:32:7

    at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)

    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)

    at Object.onceWrapper (events.js:421:26)

    at Socket.emit (events.js:314:20)

    at emitErrorNT (internal/streams/destroy.js:92:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)

    at processTicksAndRejections (internal/process/task_queues.js:84:21)

(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:8) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

(node:8) UnhandledPromiseRejectionWarning: MongoError: not master and slaveOk=false

    at Connection.<anonymous> (/node_modules/mongodb/lib/core/connection/pool.js:453:61)

    at Connection.emit (events.js:314:20)

    at processMessage (/node_modules/mongodb/lib/core/connection/connection.js:456:10)

    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connection.js:625:15)

    at Socket.emit (events.js:314:20)

    at addChunk (_stream_readable.js:297:12)

    at readableAddChunk (_stream_readable.js:272:9)

    at Socket.Readable.push (_stream_readable.js:213:10)

    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

(node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Welcome to mongo-express

------------------------



Welcome to mongo-express

------------------------
